### ISSUE TITLE
showUserPopout() not working

### ISSUE THREAD

**Issue by Teteros** [zerebos/BDPluginLibrary#218]
Seems to be a known issue, but opened an issue to track it.
Currently only affects RoleMembers from the BetterDiscordAddons repo.

**Comment by rauenzi** [comment]
The code for this was contributed by someone else and I don't have the knowledge or motivation to maintain it. If someone else wants to create a PR to fix it that would be fine, otherwise I would consider this a `wontfix`

**Comment by zerebos** [comment]
This plugin has reached EOL and will only be receiving high priority fixes!
