### ISSUE TITLE
GuildStore.getGuild(gid) not working

### ISSUE THREAD

**Issue by Kamiikaze** [zerebos/BDPluginLibrary#237]
Since few days a plugin isn't working because it can't grab the icon from the guild as `GuildStore.getGuild(gid)` always returns `undefined`.
Issue: https://github.com/samfundev/BetterDiscordStuff/issues/12

To test ist for myself i made a blank plugin with just the lib and those lines. 
```js
const selGuild = SelectedGuildStore.getGuildId()
console.log("selGuild", selGuild)

const guild = GuildStore.getGuild(selGuild)
console.log("guild", guild)
```

Thats the console output:
```console
[TestChannelTabs] version 2.6.13 has started.
selGuild 767513953525694514
guild undefined
```

**Comment by Kamiikaze** [comment]
Any news, when this will be fixed?

**Comment by zerebos** [comment]
This plugin has reached EOL and will only be receiving high priority fixes!
