### ISSUE TITLE
Zere's Plugin Library Docs README.md link

### ISSUE THREAD

**Issue by ghost** [zerebos/BDPluginLibrary#241]
In README.md it says:

> View the library documentation here: https://rauenzi.github.io/BDPluginLibrary/docs

I believe the link should be https://**zerebos**.github.io/BDPluginLibrary/docs
It seems that the original creator has changed their  GitHub username.

**Comment by zerebos** [comment]
This plugin has reached EOL and will only be receiving high priority fixes!
